---
- name: Configure FRR Repo 
  block:
    - name: Install FRR Apt Key
      ansible.builtin.apt_key:
        url: https://deb.frrouting.org/frr/keys.asc
    - name: Setup FRR Apt Repo
      ansible.builtin.apt_repository:
        repo: "deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} {{ frr_version }}"
        filename: frr

- name: Install FRR Package
  block:
    - name: Install FRR
      ansible.builtin.apt:
        pkg:
          - frr
          - frr-pythontools
